config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :edit, :update, :index]
  root to: "games#index"
  resources :games do
    resources :results
  end
  resources :follows
end

app/models/user.rb
class User < ApplicationRecord
  after_initialize :set_defaults
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, uniqueness: true
  has_one_attached :photo

  private

  def set_defaults
    at_sign = self.email.index("@").to_i - 1
    username = self.email[0..at_sign]
    self.username ||= username[0..9]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_user, only: %i[show edit update follow unfollow]

  def index
    @games = Game.all
    @user = User.find_by(username: params[:search]) if params[:search].present?
    @following = Follow.where(follower: current_user.id)
    @followers = Follow.where(followee: current_user.id)
    @results = Result.all
  end

  def show
    @following = Follow.where(follower: current_user.id)
    @followers = Follow.where(followee: current_user.id)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      redirect_to user_path(@user), notice: 'Username already taken.'
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :photo)
  end
end

app/views/users/edit.html.erb
<div class="user-container">
  <% if @user == current_user %>
    <% unless @user.username %>
      <h1>Hello, <%= @user.email %></h1>
    <% else %>
      <h1>Hello, <%= @user.username %></h1>
    <% end %>
    <div class="new-score">
      <%= simple_form_for(@user) do |f| %>
        <%= f.input :username %>
        <%= f.input :photo, as: :file %>
        <%= f.submit %>
      <% end %>
    </div>
  <% else %>
    <h1>Not You!</h1>
    <p>Don't try to edit someone else's profile!</p>
    <p>Edit <%= link_to "your profile", edit_user_path(current_user) %> instead.</p>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="user-container">
  <h1>Search Users</h1>
  <div class="search-box">
    <%= form_for "", url: users_path, role: "search", method: :get do %>
      <%= text_field_tag :search, @search_term, class:"form-control form-input", placeholder: "Search..." %>
    <% end %>
    <% if @search_term and @user.nil?%>
      <div class="search-results">
        <p><strong><%= @search_term %></strong> not found.</p>
      </div>
    <% elsif @search_term and @user %>
      <div class="search-results">
        <%= button_to @user.username, user_path(@user), class: "btn btn-wide", method: :get %>
        <% if current_user.following?(@user) %>
          <%= button_to "<i class='fa-solid fa-user-slash'></i>".html_safe, unfollow_path(@user), class: "btn btn-flat" %>
        <% else %>
          <%= button_to "<i class='fa-solid fa-user-plus'></i>".html_safe, follow_path(@user), class: "btn btn-flat" %>
        <% end %>
      </div>
    <% end %>
  </div>
  <h1>Leaderboard</h1>
  <div class="games">
    <% @games.each do |game| %>
      <% top_3 = Average.where(game: game).sort_by(&:average) %>
      <div class="leader-category">
        <h4><%= button_to game.name, game_path(game), class: "btn btn-small", method: :get %></h4>
        <% top_3[0..2].each do |avg| %>
          <div class="leader-scores">
            <p><%= link_to User.find_by(id: avg.user).username, user_path(avg.user) %></p>
            <p><%= avg.average %></p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-container">
  <h1><%= @user.username %></h1>
  <% if @user == current_user %>
    <h5><%= @user.email %></h5>
    <div class="card-product general-card">
      <% unless @user.photo.key.nil? %>
        <%= cl_image_tag @user.photo.key, class: "avatar-large" %>
      <% else %>
        <p><%= button_to "Add photo", edit_user_path(current_user), class: "btn btn-flat" %></p>
      <% end %>
      <div class="user-links">
        <p><%= button_to "Edit", edit_user_path(current_user), class: "btn btn-flat", method: :get %></p>
        <p><%= button_to "Log Out", destroy_user_session_path, class: "btn btn-flat", data: { "turbo-method": :delete } %></p>
      </div>
      <div class="follows">
        <div class="follow">
          <h4>Following</h4>
          <% if @following %>
            <% @following.each do |friend| %>
              <div class="user-small">
                <%= link_to User.find(friend.followee).username, user_path(User.find(friend.followee)) %>
                <% unless Follow.where(follower: current_user.id, followee: friend.followee).empty? %>
                  <%= link_to "<i class='fa-solid fa-user-slash'></i>".html_safe, follow_path(Follow.where(follower: current_user.id, followee: friend.followee).first), data: { turbo_method: :delete }, class: "btn btn-small" %>
                <% else %>
                  <%= link_to "<i class='fa-solid fa-user-plus'></i>".html_safe, follows_path(follower: current_user.id, followee: friend.followee), data: { turbo_method: :post }, class: "btn btn-small" %>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </div>
        <div class="follow">
          <h4>Followers</h4>
          <% if @followers %>
            <% @followers.each do |friend| %>
              <div class="user-small">
              <%= link_to User.find(friend.follower).username, user_path(User.find(friend.follower)) %>
              <% unless Follow.where(follower: current_user.id, followee: friend.follower).empty? %>
                <%= link_to "<i class='fa-solid fa-user-slash'></i>".html_safe, follow_path(Follow.where(follower: current_user.id, followee: friend.follower).first), data: { turbo_method: :delete }, class: "btn btn-small" %>
              <% else %>
                <%= link_to "<i class='fa-solid fa-user-plus'></i>".html_safe, follows_path(follower: current_user.id, followee: friend.follower), data: { turbo_method: :post }, class: "btn btn-small" %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% else %>
    <div class="card-product">
      <% unless @user.photo.key.nil? %>
        <%= cl_image_tag @user.photo.key, class: "avatar-large" %>
      <% else %>
        <p><%= image_tag "https://i.imgur.com/djGIukc.png", class: "avatar-large" %></p>
      <% end %>
      <div class="card-product-infos">
        <% unless Follow.where(follower: current_user.id, followee: @user.id).empty? %>
          <%= link_to "<i class='fa-solid fa-user-slash'></i>".html_safe, follow_path(Follow.where(follower: current_user.id, followee: @user.id).first), data: { turbo_method: :delete }, class: "btn btn-flat" %>
        <% else %>
          <%= link_to "<i class='fa-solid fa-user-plus'></i>".html_safe, follows_path(follower: current_user.id, followee: @user.id), data: { turbo_method: :post }, class: "btn btn-flat" %>
        <% end %>
        <p><%= button_to "Me", user_path(current_user), class: "btn btn-flat", method: :get %></p>
      </div>
    </div>
  <% end %>
</div>