config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :edit, :update, :index]
  root to: "games#index"
  resources :games do
    resources :results
  end
  resources :follows
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="navbar-brand">
      <%= link_to root_path do %>
        <%= image_tag "https://i.imgur.com/ozA6JYB.png" %>
      <% end %>
      <% if cookies[:theme] == "light" %>
        <%= link_to "<i class='fa-solid fa-moon'></i>".html_safe, root_path(theme: "dark") %>
      <% else %>
        <%= link_to "<i class='fa-solid fa-sun'></i>".html_safe, root_path(theme: "light") %>
      <% end %>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Games", games_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Users", users_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Profile", user_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Sign Out", destroy_user_session_path, data: { "turbo-method": :delete }, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>