config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :edit, :update, :index]
  root to: "games#index"
  resources :games do
    resources :results
  end
  resources :follows
end

app/models/result.rb
class Result < ApplicationRecord
  # belongs_to :user
  # belongs_to :game
  # default_scope :order => "edition"

  def get_score(guess)
    as_array = guess.split()
    if as_array[0] == "Wordle"
      score = as_array[2][0]
      score = 7 if score == "X"
      return score
    end
    if as_array[0] == "Framed"
      as_array[3..8].each_with_index do |line, index|
        return index + 1 if line == "🟩"
      end
      return 7
    end
    if as_array[1] == "NewsGuesser"
      score = as_array[3].index("🟩")
      return 7 if score.nil?
      return score + 1
    end
    if as_array[0] == "Poeltl"
      score = as_array[3][0]
      score = 9 if score == "X"
      return score
    end
    if as_array[2] == "contexto.me"
      return as_array[8].to_i
    end
  end

  def get_edition(guess)
    as_array = guess.split()
    if as_array[0] == "Framed"
      return as_array[1]
    end
    if as_array[0] == "Wordle"
      return "##{as_array[1]}"
    end
    if as_array[1] == "NewsGuesser"
      edition = as_array[2]
      year = Time.now.year.to_s
      short_year = year[2..3]
      return edition.sub!(year, short_year)
    end
    if as_array[0] == "Poeltl"
      return "##{as_array[1]}"
    end
    if as_array[2] == "contexto.me"
      return as_array[3]
    end
  end

  def get_edition_int(guess)
    as_array = guess.split()
    if as_array[0] == "Framed"
      return as_array[1].delete("#").to_i
    end
    if as_array[0] == "Wordle"
      return as_array[1].to_i
    end
    if as_array[1] == "NewsGuesser"
      edition = as_array[2]
      return (Date.parse(edition) - Date.parse("1/1/2023")).to_i
    end
    if as_array[0] == "Poeltl"
      return as_array[1].to_i
    end
    if as_array[2] == "contexto.me"
      return as_array[3].delete("#").to_i
    end
  end

  def get_display_score(guess)
    as_array = guess.split()
    if as_array[0] == "Wordle"
      score = as_array[2][0]
      score = 7 if score == "X"
      return "#{score}/6"
    end
    if as_array[0] == "Framed"
      as_array[3..8].each_with_index do |line, index|
        return "#{index + 1}/6" if line == "🟩"
      end
      return "7/6"
    end
    if as_array[1] == "NewsGuesser"
      score = as_array[3].index("🟩")
      return "7/6" if score.nil?
      return "#{score + 1}/6"
    end
    if as_array[0] == "Poeltl"
      score = as_array[3][0]
      score = 9 if score == "X"
      return "#{score}/8"
    end
    if as_array[2] == "contexto.me"
      return as_array[8]
    end
  end

  def clean(guess)
    as_array = guess.split()
    return as_array[3..as_array.size - 2].join() if as_array[0] == "Framed"
    return as_array[3..] if as_array[0] == "Wordle"
    return as_array[3] if as_array[1] == "NewsGuesser"
    if as_array[0] == "Poeltl"
      poetl_guess = as_array[6..]
      return poetl_guess
    end
    if as_array[2] == "contexto.me"
      temp = as_array[-6..as_array.length]
      tips = "#{as_array[11]} tips :(" if as_array[12] == "tips."
      tips = "1 tip :(" if as_array[12] == "tips." && as_array[11].to_i == 1
      return [tips, "#{temp[0]} #{temp[1]}", "#{temp[2]} #{temp[3]}", "#{temp[4]} #{temp[5]}"] if as_array[12] == "tips."
      return ["#{temp[0]} #{temp[1]}", "#{temp[2]} #{temp[3]}", "#{temp[4]} #{temp[5]}"]
    end
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
    @game = Game.find(params[:game_id])
    @average = get_average(@game, current_user)
    @results = Result.where(game: @game.id, user: current_user)
    @results = @results.sort_by(&:edition_int).reverse
    @results = @results.paginate(:page => params[:page], per_page: 8)
    # @results = @results.paginate(:page => params[:page])
    # @results = @results.reorder("edition")
  end

  def new
    @game = Game.find(params[:game_id])
    @result = Result.new
  end

  def create
    @game = Game.find(params[:game_id])
    @result = Result.new(result_params)
    @result.user = current_user.id
    @result.game = @game.id
    @result.score = @result.get_score(@result.guess)
    @result.edition = @result.get_edition(@result.guess)
    @result.display_score = @result.get_display_score(@result.guess)
    @result.edition_int = @result.get_edition_int(@result.guess)
    unless @result.score.nil?
      @result.save!
      set_average(@game, current_user)
      redirect_to game_result_path(@game, @result), notice: 'Result noted.'
    else
      redirect_to new_game_result_path(@game), notice: 'Result not valid, try again.'
    end
  end

  def show
    @game = Game.find(params[:game_id])
    @result = Result.find(params[:id])
    @user = User.find(@result.user)
    @edition = @result.edition
    @friends = Follow.where(followee: current_user.id)
    @results = Result.where(game: @game, edition: @edition)
    @leader = User.find(@results.min_by(&:score).user)
  end

  def edit
    @game = Game.find(params[:game_id])
    @result = Result.find(params[:id])
  end

  def update
    @game = Game.find(params[:game_id])
    @result = Result.find(params[:id])
    @result.score = @result.get_score(@result.guess)
    @result.edition = @result.get_edition(@result.guess)
    @result.display_score = @result.get_display_score(@result.guess)
    @result.edition_int = @result.get_edition_int(@result.guess)
    @average = set_average(@game, current_user)
    if @result.update(result_params)
      redirect_to game_result_path(@game, @result)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @game = Game.find(params[:game_id])
    @result = Result.find(params[:id])
    @result.destroy!
    redirect_to game_results_path(@game), status: :see_other
  end

  private

  def result_params
    params.require(:result).permit(:user, :score, :guess, :game)
  end

  def set_average(game, user)
    results = Result.where(game: @game, user: current_user)
    if Average.find_by(game: game, user: user).nil?
      avg = Average.create!(game: game, user: user, average: results.first.score)
    else
      avg = Average.find_by(game: game, user: user)
      sum_score = 0
      results.each do |result|
        sum_score += result.score.to_i
      end
      avg.average = '%.2f' % (sum_score / results.size.to_f)
      avg.save!
    end
    return avg
  end

  def get_average(game, user)
    return 0 unless Average.find_by(game: game, user: user).nil?
    return Average.find_by(game: game, user: user)
  end
end

app/views/results/edit.html.erb
<div class="result-container">
  <h1>Edit Result</h1>
  <div class="new-score">
    <%= simple_form_for [@game, @result] do |f| %>
      <%= f.input :guess, :input_html => {:rows => 10}, label: false %>
      <%= f.submit class: "btn btn-wide" %>
    <% end %>
    <%= link_to game_result_path(@game, @result), data: {turbo_method: :delete, turbo_confirm: "Delete?"} do %>
      <p><i class="fa-regular fa-trash-can"></i></p>
    <% end %>
  </div>
</div>

app/views/results/index.html.erb
<div class="result-container">
  <h1><%= @game.name %></h1>
  <div class="result-links">
    <p><%= button_to "Info", game_path(@game), class: "btn btn-flat", method: :get %></p>
    <p><%= button_to "Play", @game.url, class: "btn btn-flat", form: { target: "_blank" }, method: :get %></p>
    <p><%= button_to "Record", new_game_result_path(@game), class: "btn btn-flat", method: :get %></p>
  </div>
  <% unless @results.nil? %>
    <div class="average-show">
      <% unless @average.nil? || @average == 0 %>
        <h3>Average: <strong><%= @average.average %></strong></h3>
      <% end %>
    </div>
    <div class="cards">
      <% @results.sort_by(&:edition_int).reverse.each do |result| %>
        <div class="result-category">
          <div class="result-info">
            <% unless result.edition.nil? and result.score.nil? %>
              <h2><%= link_to "#{result.edition}", game_result_path(@game, result) %></h2>
              <h4><%= link_to "#{result.display_score}", game_result_path(@game, result) %></h4>
            <% else %>
              <p>Invalid.</p>
            <% end %>
            </div>
          <div class="change-links">
            <%= link_to "<i class='fa-solid fa-pen-to-square'></i>".html_safe, edit_game_result_path(@game, result) %>
            <%= link_to game_result_path(@game, result), data: {turbo_method: :delete, turbo_confirm: "Delete?"} do %>
              <i class="fa-regular fa-trash-can"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <%= will_paginate @results %>
  <% end %>
</div>

app/views/results/new.html.erb
<div class="game-container">
  <h1>New <%= @game.name %> Score</h1>
  <div class="result-links">
    <p><%= button_to "Scores", game_results_path(@game), class: "btn btn-flat", method: :get %></p>
    <p><%= button_to "Play", @game.url, class: "btn btn-flat", form: { target: "_blank" }, method: :get %></p>
    <p><%= button_to "Record", new_game_result_path(@game), class: "btn btn-flat", method: :get %></p>
  </div>
  <div class="new-score">
    <%= simple_form_for [@game, @result] do |f| %>
      <%= f.input :guess, :input_html => {:rows => 10}, label: false %>
      <%= f.submit class: "btn btn-wide" %>
    <% end %>
  </div>
</div>

app/views/results/show.html.erb
<div class="game-container">
  <h1><%= @game.name %> <%= @result.edition %></h1>
  <div class="result-links">
    <p><%= button_to "Scores", game_results_path(@game), class: "btn btn-flat", method: :get %></p>
    <p><%= button_to "Play", @game.url, class: "btn btn-flat", form: { target: "_blank" }, method: :get %></p>
    <p><%= button_to "Record", new_game_result_path(@game), class: "btn btn-flat", method: :get %></p>
  </div>
  <div class="game-stats">
    <div class="game-big">
      <h3><%= @user.username %></h3>
      <% unless @result.edition.nil? and @result.score.nil? %>
        <div class="game-guess">
          <h5><%= @result.display_score %></h5> <!-- Not strong enough -->
          <% if @result.clean(@result.guess).kind_of?(Array) %>
            <% @result.clean(@result.guess).each do |line| %>
              <%= line %>
              <br>
            <% end %>
          <% else %>
            <%= @result.clean(@result.guess) %>
          <% end %>
        </div>
      <% else %>
        <p>Invalid score!</p>
      <% end %>
    </div>
    <div class="game-big">
      <h3><%= @result.edition %>'s Stats</h3>
      <% unless @result.edition.nil? and @result.score.nil? %>
        <div class="game-statistic">
          <div class="game-stat">
            <strong>Leader:</strong>
            <% if @leader.photo.key.nil? %>
              <%= link_to (image_tag "https://i.imgur.com/djGIukc.png", class: "avatar-small"), user_path(@leader) %>
            <% else %>
              <%= link_to (cl_image_tag @leader.photo.key, class: "avatar-small"), user_path(@leader) %>
            <% end %>
          </div>
          <div class="game-stat">
            <strong>Played:</strong>
            <%= @results.size %>
          </div>
          <div class="game-stat">
            <strong>Best:</strong>
            <%= @results.sort_by(&:score).first.score %>
          </div>
          <div class="game-stat">
            <strong>Worst:</strong>
            <%= @results.sort_by(&:score).reverse.first.score %>
          </div>
        </div>
      <% else %>
        <p>Invalid score!</p>
      <% end %>
    </div>
  </div>
</div>
<% unless @friends.nil? %>
  <div class="friends-container">
    <h2>Friends</h2>
    <div class="cards">
      <% @friends.each do |friend| %>
        <% if Average.find_by(game: @game, user: friend) %>
          <div class="game">
            <h4><%= link_to friend.username, user_path(friend) %></h4>
            <% friend_result = Result.find_by(user: friend, edition: @result.edition, game: @game) %>
            <div class="friend-score">
              <% unless friend_result.nil? %>
                <%= button_to friend_result.display_score, game_result_path(@game, friend_result), class: "btn btn-score", method: :get %>
              <% else %>
                Unplayed
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>