config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :edit, :update, :index]
  root to: "games#index"
  resources :games do
    resources :results
  end
  resources :follows
end

app/models/game.rb
class Game < ApplicationRecord
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index ]
  def index
    @games = Game.all
    @my_games = Result.where(user: current_user).map { |result| @my_games << result.game }.uniq
    @other_games = find_other(@my_games)
  end

  def new
    @game = Game.new if current_user.id == 1
  end

  def create
    @game = Game.new(game_params) if current_user.id == 1
    @game.user = current_user
    @game.save ? (redirect_to game_path(@game), notice: 'Game was successfully created.') : (render :new, status: :unprocessable_entity)
  end

  def edit
    @game = Game.find(params[:id]) if current_user.id == 1
  end

  def update
    @game = Game.update!(game_params) if current_user.id == 1
    redirect_to game_path(@game), notice: "Game was successfully updated."
  end

  def show
    @game = Game.find(params[:id])
    @everyone_results = Result.where(game: @game)
    @everyone_average = '%.2f' % @everyone_results.average("score") unless @everyone_results.empty?
    @user_results = Result.where(game: @game, user: current_user)
    @user_average = Average.find_by(game: @game, user: current_user).average if Average.find_by(game: @game, user: current_user)
  end

  private

  def find_other(my_games)
    temp = []
    Game.ids.each { |game| temp << game unless my_games.include? game }
    temp
  end

  def game_params
    params.require(:game).permit(:name, :url)
  end
end

app/views/games/edit.html.erb
<div class="game-container">
  <h2>Edit Game</h2>
  <% unless @game.nil? %>
    <div class="form-group" style="width: 80%; margin: auto;" >
      <%= simple_form_for @game, data:{ turbo: false } do |f| %>
        <%= f.input :name, required: true  %>
        <%= f.input :url, required: true %>
        <%= f.input :max_score, required: true %>
        <%= f.submit %>
      <% end %>
    </div>
  <% else %>
    <p>Only an admin can edit a  game</p>
  <% end %>
</div>

app/views/games/index.html.erb
<div class="game-container">
  <h1>Daily Games Score</h1>
  <% unless current_user %>
    <div class="logged-out">
      <p>Keep track of all your daily Wordle-inspired game scores.</p>
      <p>Easily share your scores with friends and groups in one place.</p>
      <p><%= button_to "Start now", new_user_registration_path, class: "btn btn-wide", method: :get %></p>
    </div>
  <% end %>
<% if current_user %>
    <div class="result-links">
      <p><%= link_to "My Games", "javascript:myGames()", class: "btn btn-js  btn-active", id: "btn-my-games" %></p>
      <p><%= link_to "All Games", "javascript:allGames()", class: 'btn btn-js', id: "btn-all-games" %></p>
    </div>
    <% if @games.size > 3 %>
      <div class="games">
    <% else %>
      <div class="games-small">
    <% end %>
    <% @my_games.each do |game| %>
        <div class="game">
          <h5><%= link_to Game.find(game).name, game_path(Game.find(game)) %><h5>
          <div class="quick-links">
            <p><%= button_to "<i class='fa-solid fa-list'></i>".html_safe, game_results_path(Game.find(game)), class: "btn btn-small", method: :get %></p>
            <p><%= button_to "<i class='fa-solid fa-play'></i>".html_safe, Game.find(game).url, class: "btn btn-small", form: { target: "_blank" }, method: :get %></p>
            <p><%= button_to "<i class='fa-solid fa-floppy-disk'></i>".html_safe, new_game_result_path(Game.find(game)), class: "btn btn-small", method: :get %></p>
          </div>
        </div>
      <% end %>
      <% if @other_games.size > 0 %>
        <% @other_games.each do |game| %>
          <div class="game all-games games-all" id="all-games">
            <h5><%= link_to Game.find(game).name, game_path(Game.find(game)) %><h5>
            <div class="quick-links">
              <p><%= button_to "<i class='fa-solid fa-list'></i>".html_safe, game_results_path(Game.find(game)), class: "btn btn-small", method: :get %></p>
              <p><%= button_to "<i class='fa-solid fa-play'></i>".html_safe, Game.find(game).url, class: "btn btn-small", form: { target: "_blank" }, method: :get %></p>
              <p><%= button_to "<i class='fa-solid fa-floppy-disk'></i>".html_safe, new_game_result_path(Game.find(game)), class: "btn btn-small", method: :get %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  <% else %>
    <% if @games.size > 3 %>
      <div class="games">
    <% else %>
      <div class="games-small">
    <% end %>
    <% @games.each do |game| %>
        <div class="game">
          <h5><%= link_to game.name, game_path(game) %><h5>
          <div class="quick-links">
            <p><%= button_to "<i class='fa-solid fa-list'></i>".html_safe, game_results_path(game), class: "btn btn-small", method: :get %></p>
            <p><%= button_to "<i class='fa-solid fa-play'></i>".html_safe, game.url, class: "btn btn-small", form: { target: "_blank" }, method: :get %></p>
            <p><%= button_to "<i class='fa-solid fa-floppy-disk'></i>".html_safe, new_game_result_path(game), class: "btn btn-small", method: :get %></p>
          </div>
        </div>
    <% end %>
  <% end %>
</div>
<script>
  function allGames() {
    var x = document.getElementsByClassName("games-all");
    for (let i = 0; i < x.length; i++) {
      x[i].classList.remove("all-games");
    };
    document.getElementById("btn-my-games").classList.remove("btn-active");
    document.getElementById("btn-all-games").classList.add("btn-active");
  }
  function myGames() {
    var x = document.getElementsByClassName("games-all");
    for (let i = 0; i < x.length; i++) {
      x[i].classList.add("all-games");
    };
    document.getElementById("btn-all-games").classList.remove("btn-active");
    document.getElementById("btn-my-games").classList.add("btn-active");
  }
</script>

app/views/games/new.html.erb
<!--
<div class="game-container">
  <h2>Add a New Game:</h2>
    <div class="form-group" style="width: 80%" >
      <%= simple_form_for @game, data:{ turbo: false } do |f| %>
        <%= f.input :name, required: true  %>
        <%= f.input :url, required: true %>
        <%= f.submit %>
      <% end %>
    </div>
</div>
-->

app/views/games/show.html.erb
<div class="game-container">
  <h1><%= @game.name %></h1>
  <div class="result-links">
    <p><%= button_to "Scores", game_results_path(@game), class: "btn btn-flat", method: :get %></p>
    <p><%= button_to "Play", @game.url, class: "btn btn-flat", form: { target: "_blank" }, method: :get %></p>
    <p><%= button_to "Record", new_game_result_path(@game), class: "btn btn-flat", method: :get %></p>
  </div>
  <div class="statistics-container">
    <h2>Statistics</h2>
    <% if @user_results.size > 0 %>
      <div class="statistics">
        <div class="statistic">
          <h3><%= current_user.username %></h3>
          <div class="stat">
            <strong>Average:</strong>
            <%= @user_average %>
          </div>
          <div class="stat">
            <strong>Played:</strong>
            <%= @user_results.size %>
          </div>
          <div class="stat">
            <strong>Best:</strong>
            <%= @user_results.sort_by(&:score).first.score %>
          </div>
          <div class="stat">
            <strong>Win %:</strong>
            <% unless @game.max_score.nil? %>
              <%= '%.2f' % (((@user_results.select{|result| result.score < @game.max_score+1 }.size) / @user_results.size.to_f) * 100) %>
            <% else %>
              100%
            <% end %>
          </div>
        </div>
      <% else %>
        <div class="statistics">
          <div class="statistic">
            <h3><%= current_user.username %></h3>
            <p>No scores</p>
            <p>Play now</p>
          </div>
      <% end %>
      <% if @everyone_results.size > 0 %>
        <div class="statistic">
          <h3>Everyone</h3>
          <div class="stat">
            <strong>Average:</strong>
            <%= @everyone_average %>
          </div>
          <div class="stat">
            <strong>Played:</strong>
            <%= @everyone_results.size %>
          </div>
          <div class="stat">
            <strong>Best:</strong>
            <%= @everyone_results.sort_by(&:score).first.score %>
          </div>
          <div class="stat">
            <strong>Win %:</strong>
            <% unless @game.max_score.nil? %>
              <%= '%.2f' % (((@everyone_results.select{|result| result.score < @game.max_score+1 }.size) / @everyone_results.size.to_f) * 100) %>
            <% else %>
              100%
            <% end %>
          </div>
        </div>
      <% else %>
          <div class="statistic">
            <h3>Everyone</h3>
            <p>No scores</p>
            <p>Play now</p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <% unless @game.max_score.nil? %>
    <div class="distributions">
      <h3>Distribution</h3>
      <% if @user_results.size > 0 %>
        <div class="distribution">
          <% i = 0 %>
          <% while i < @game.max_score %>
            <div class="distribution-value">
              <strong><%= i + 1 %></strong>
              <%= @user_results.select{|result| result.score == (i + 1) }.size %>
            </div>
            <% i += 1 %>
          <% end %>
          <div class="distribution-value">
            <strong>X</strong>
            <%= @user_results.select{|result| result.score == (@game.max_score + 1) }.size %>
          </div>
        </div>
      <% else %>
        <p>You haven't played yet.</p>
      <% end %>
    </div>
  <% end %>
</div>